pipeline {
   agent any

   stages {
      environment {
        ARTIFACTORY_SERVER_ID = credentials('artifactory_server_id')
        ARTIFACTORY_SERVER_URL = credentials('artifactory_server_url')
        ARTIFACTORY_CREDENTIALS = credentials('artifactory_credentials')
      }
      stage('Test') {
          steps {
             sh '''
                 ./gradlew test
               '''
          }
      }
      
      stage('Build') {
          steps {
              sh '''
                 ./gradlew clean build
                '''
          }
      }

      stage('Publish Artifactory') {
        steps {
            rtServer (
                id: env.ARTIFACTORY_SERVER_ID,
                url: env.ARTIFACTORY_SERVER_URL,
                username: env.ARTIFACTORY_CREDENTIALS_USR,
                password: env.ARTIFACTORY_CREDENTIALS_PSW
            )
            rtUpload (
                serverId: env.ARTIFACTORY_SERVER_ID,
                    spec: '''{
                        "files": [
                            {
                            "pattern": "build/libs/*.war",
                            "target": "gradle-release-local/poc-rest-service/"
                            }
                        ]
                    }'''
            )
        }
      }
   }
}

