pipeline {
   agent any

   stages {
      stage('Download Docker image') {
         steps {
            sh '''
                 docker pull gabikersul/poc-rest-service:rest-service-app
               '''
         }
      }

      stage('Run Docker image') {
         steps {
            sh '''
                 docker run -d -p 8083:8083 gabikersul/poc-rest-service:rest-service-app
               '''
         }
      }
   }
}